baseURL: "https://koolgax99.github.io/"
title: koolgax99
paginate: 5
theme: PaperMod
publishDir: "docs"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: koolgax99
  description: "I am Nihar Sanda"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Koolgax99"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: koolgax99
    subtitle: "Hi, I am Nihar Sanda"
    imageUrl: "nihar.webp"
    imageWidth: 150
    imageHeight: 150
    imageTitle: Nihar Sanda
    buttons:
      - name: Resume
        url: "NiharSandaResume.pdf"
      - name: About
        url: about
      - name: Projects
        url: projects

  socialIcons: # optional
    - name: Github
      url: "https://github.com/koolgax99"
    - name: "Twitter"
      url: "https://twitter.com/nsanda10"
    - name: "LinkedIn"
      url: "https://in.linkedin.com/in/nihar-sanda-07ab6118b"
    - name: "medium"
      url: "https://koolgax99.medium.com/"
    - name: "email"
      url: "nihar.sanda@gmail.com"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: about
      url: /about/
      weight: 10
    - identifier: projects
      name: projects
      url: /projects/
      weight: 20
    - identifier: Camp+
      name: Camp+
      url: https://camplus.network/
      weight: 30
